"""create leads table

Revision ID: 0ac9f8adb27c
Revises: 
Create Date: 2026-09-21 22:25:43.355276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac9f8adb27c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('h3_hex_id', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('category', sa.Enum('DIGITAL_GHOST', 'DIGITAL_DINOSAUR', 'LAGGY_UX', 'AUTOMATION_CANDIDATE', name='lead_category'), nullable=False),
    sa.Column('has_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_mobile_responsive', sa.Boolean(), nullable=False),
    sa.Column('ttfb_ms', sa.Integer(), nullable=False),
    sa.Column('dom_load_time_ms', sa.Integer(), nullable=False),
    sa.Column('detected_tech', sa.JSON(), nullable=False),
    sa.Column('llm_audit_summary', sa.Text(), nullable=True),
    sa.Column('lacks_chat_widget', sa.Boolean(), nullable=True),
    sa.Column('lacks_booking_flow', sa.Boolean(), nullable=True),
    sa.Column('origin_source_url', sa.Text(), nullable=False),
    sa.Column('extraction_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUDITED', 'CONTACTED_WHATSAPP', 'CONTACTED_EMAIL', 'RESPONDED', 'CONVERTED', 'OPTED_OUT', name='outreach_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_category'), 'leads', ['category'], unique=False)
    op.create_index(op.f('ix_leads_h3_hex_id'), 'leads', ['h3_hex_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_h3_hex_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_category'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
